# Copyright (c) 2021 Concurrent Technologies Corporation.
#                                                                                                               
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at                                                    
#                                                                                                               
#     http://www.apache.org/licenses/LICENSE-2.0                                                                
#                                                                                                               
# Unless required by applicable law or agreed to in writing, software is distributed under the License is       
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or              
# implied.  See the License for the specific language governing permissions and limitations under the License.  

---
name: Build Native
description: Reusable action for building native code using docker
inputs:
  os-name:
    description: 'OS Name (runs-on value)'
    required: true
  docker-image:
    description: 'Docker image to use'
    required: true
  library-filename:
    description: 'Filename of library file (libomega_edit.so, libomega_edit.dylib or omega_edit.dll)'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up QEMU 🔧
      uses: docker/setup-qemu-action@v1
      with:
        platforms: arm64

    - name: Start container 🐳
      shell: bash
      run: |
        docker run \
          --memory "12g" \
          --cpus "3" \
          -d \
          --name omega-edit-${{ inputs.os-name }}-cont \
          -v $PWD:/omega-edit \
          -w /omega-edit \
          ${{ inputs.docker-image }} \
          bash -c "tail -f /dev/null"

    - name: Perform cmake operators 🔧
      shell: bash
      run: docker exec omega-edit-${{ inputs.os-name }}-cont bash -c "(make clean || true) && make TYPE=Release all"

    - name: Copy library file from docker container 🔻
      shell: bash
      run: |
        rm -rf _install/lib/ || true
        mkdir -p _install/lib || true
        docker cp \
          omega-edit-${{ inputs.os-name }}-cont:/omega-edit/lib/${{ inputs.library-filename }} \
          ${{ inputs.library-filename }}

    - name: Upload Native Library (${{ inputs.os-name }}-${{ inputs.library-filename }}) 🔺
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.os-name }}-${{ inputs.library-filename }}
        path: ${{ inputs.library-filename }}

    - name: Remove container and image 🧹
      shell: bash
      if: success() || failure()
      run: |
        docker kill omega-edit-${{ inputs.os-name }}-cont
        docker rm -f omega-edit-${{ inputs.os-name }}-cont
        docker rmi -f ${{ inputs.docker-image }}
