/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class omega_editJNI {
  public final static native long omega_change_get_offset(long jarg1);
  public final static native long omega_change_get_length(long jarg1);
  public final static native long omega_change_get_serial(long jarg1);
  public final static native char omega_change_get_kind_as_char(long jarg1);
  public final static native long omega_change_get_bytes(long jarg1);
  public final static native int omega_change_is_undone(long jarg1);
  public final static native int omega_check_model(long jarg1);
  public final static native int OMEGA_VIEWPORT_CAPACITY_LIMIT_get();
  public final static native int OMEGA_SEARCH_PATTERN_LENGTH_LIMIT_get();
  public final static native long omega_edit_create_session(String jarg1, long jarg2, long jarg3);
  public final static native void omega_edit_destroy_session(long jarg1);
  public final static native long omega_edit_create_viewport(long jarg1, long jarg2, long jarg3, long jarg4, long jarg5);
  public final static native void omega_edit_destroy_viewport(long jarg1);
  public final static native int omega_edit_clear_changes(long jarg1);
  public final static native long omega_edit_undo_last_change(long jarg1);
  public final static native long omega_edit_redo_last_undo(long jarg1);
  public final static native int omega_edit_save(long jarg1, String jarg2, int jarg3);
  public final static native long omega_edit_delete(long jarg1, long jarg2, long jarg3);
  public final static native long omega_edit_insert_bytes(long jarg1, long jarg2, long jarg3, long jarg4);
  public final static native long omega_edit_insert(long jarg1, long jarg2, String jarg3, long jarg4);
  public final static native long omega_edit_overwrite_bytes(long jarg1, long jarg2, long jarg3, long jarg4);
  public final static native long omega_edit_overwrite(long jarg1, long jarg2, String jarg3, long jarg4);
  public final static native String omega_license_get();
  public final static native long omega_search_create_context_bytes(long jarg1, long jarg2, long jarg3, long jarg4, long jarg5, int jarg6);
  public final static native long omega_search_create_context(long jarg1, String jarg2, long jarg3, long jarg4, long jarg5, int jarg6);
  public final static native long omega_search_context_get_offset(long jarg1);
  public final static native long omega_search_context_get_length(long jarg1);
  public final static native int omega_search_next_match(long jarg1, long jarg2);
  public final static native void omega_search_destroy_context(long jarg1);
  public final static native String omega_session_get_file_path(long jarg1);
  public final static native long omega_session_get_user_data(long jarg1);
  public final static native long omega_session_get_num_viewports(long jarg1);
  public final static native long omega_session_get_num_changes(long jarg1);
  public final static native long omega_session_get_num_undone_changes(long jarg1);
  public final static native long omega_session_get_computed_file_size(long jarg1);
  public final static native long omega_session_get_last_change(long jarg1);
  public final static native long omega_session_get_last_undo(long jarg1);
  public final static native long omega_session_get_change(long jarg1, long jarg2);
  public final static native int omega_session_viewport_on_change_callbacks_paused(long jarg1);
  public final static native void omega_session_pause_viewport_on_change_callbacks(long jarg1);
  public final static native void omega_session_resume_viewport_on_change_callbacks(long jarg1);
  public final static native String omega_change_get_string(long jarg1);
  public final static native String omega_viewport_get_string(long jarg1);
  public final static native long omega_edit_insert_string(long jarg1, long jarg2, String jarg3);
  public final static native long omega_edit_overwrite_string(long jarg1, long jarg2, String jarg3);
  public final static native long omega_search_create_context_string__SWIG_0(long jarg1, String jarg2, long jarg3, long jarg4, int jarg5);
  public final static native long omega_search_create_context_string__SWIG_1(long jarg1, String jarg2, long jarg3, long jarg4);
  public final static native long omega_search_create_context_string__SWIG_2(long jarg1, String jarg2, long jarg3);
  public final static native long omega_search_create_context_string__SWIG_3(long jarg1, String jarg2);
  public final static native int omega_version_major();
  public final static native int omega_version_minor();
  public final static native int omega_version_patch();
  public final static native int omega_version();
  public final static native long omega_viewport_get_session(long jarg1);
  public final static native long omega_viewport_get_capacity(long jarg1);
  public final static native long omega_viewport_get_length(long jarg1);
  public final static native long omega_viewport_get_data(long jarg1);
  public final static native int omega_viewport_has_changes(long jarg1);
  public final static native long omega_viewport_get_offset(long jarg1);
  public final static native long omega_viewport_get_user_data(long jarg1);
  public final static native int omega_viewport_update(long jarg1, long jarg2, long jarg3);
  public final static native void omega_viewport_execute_on_change(long jarg1, long jarg2);
  public final static native int omega_visit_changes(long jarg1, long jarg2, long jarg3);
  public final static native int omega_visit_changes_reverse(long jarg1, long jarg2, long jarg3);
  public final static native long omega_visit_change_create_context(long jarg1, int jarg2);
  public final static native int omega_visit_change_next(long jarg1);
  public final static native long omega_visit_change_context_get_change(long jarg1);
  public final static native void omega_visit_change_destroy_context(long jarg1);
}
