/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class omega_edit implements omega_editConstants {
  public static long omega_change_get_offset(SWIGTYPE_p_omega_change_t change_ptr) {
    return omega_editJNI.omega_change_get_offset(SWIGTYPE_p_omega_change_t.getCPtr(change_ptr));
  }

  public static long omega_change_get_length(SWIGTYPE_p_omega_change_t change_ptr) {
    return omega_editJNI.omega_change_get_length(SWIGTYPE_p_omega_change_t.getCPtr(change_ptr));
  }

  public static long omega_change_get_serial(SWIGTYPE_p_omega_change_t change_ptr) {
    return omega_editJNI.omega_change_get_serial(SWIGTYPE_p_omega_change_t.getCPtr(change_ptr));
  }

  public static char omega_change_get_kind_as_char(SWIGTYPE_p_omega_change_t change_ptr) {
    return omega_editJNI.omega_change_get_kind_as_char(SWIGTYPE_p_omega_change_t.getCPtr(change_ptr));
  }

  public static SWIGTYPE_p_omega_byte_t omega_change_get_bytes(SWIGTYPE_p_omega_change_t change_ptr) {
    long cPtr = omega_editJNI.omega_change_get_bytes(SWIGTYPE_p_omega_change_t.getCPtr(change_ptr));
    return (cPtr == 0) ? null : new SWIGTYPE_p_omega_byte_t(cPtr, false);
  }

  public static int omega_change_is_undone(SWIGTYPE_p_omega_change_t change_ptr) {
    return omega_editJNI.omega_change_is_undone(SWIGTYPE_p_omega_change_t.getCPtr(change_ptr));
  }

  public static int omega_check_model(SWIGTYPE_p_omega_session_t session_ptr) {
    return omega_editJNI.omega_check_model(SWIGTYPE_p_omega_session_t.getCPtr(session_ptr));
  }

  public static SWIGTYPE_p_omega_session_t omega_edit_create_session(String file_path, SWIGTYPE_p_f_p_q_const__omega_session_t_p_q_const__omega_change_t__void cbk, SWIGTYPE_p_void user_data_ptr) {
    long cPtr = omega_editJNI.omega_edit_create_session(file_path, SWIGTYPE_p_f_p_q_const__omega_session_t_p_q_const__omega_change_t__void.getCPtr(cbk), SWIGTYPE_p_void.getCPtr(user_data_ptr));
    return (cPtr == 0) ? null : new SWIGTYPE_p_omega_session_t(cPtr, false);
  }

  public static void omega_edit_destroy_session(SWIGTYPE_p_omega_session_t session_ptr) {
    omega_editJNI.omega_edit_destroy_session(SWIGTYPE_p_omega_session_t.getCPtr(session_ptr));
  }

  public static SWIGTYPE_p_omega_viewport_t omega_edit_create_viewport(SWIGTYPE_p_omega_session_t session_ptr, long offset, long capacity, SWIGTYPE_p_f_p_q_const__omega_viewport_t_p_q_const__omega_change_t__void cbk, SWIGTYPE_p_void user_data_ptr) {
    long cPtr = omega_editJNI.omega_edit_create_viewport(SWIGTYPE_p_omega_session_t.getCPtr(session_ptr), offset, capacity, SWIGTYPE_p_f_p_q_const__omega_viewport_t_p_q_const__omega_change_t__void.getCPtr(cbk), SWIGTYPE_p_void.getCPtr(user_data_ptr));
    return (cPtr == 0) ? null : new SWIGTYPE_p_omega_viewport_t(cPtr, false);
  }

  public static void omega_edit_destroy_viewport(SWIGTYPE_p_omega_viewport_t viewport_ptr) {
    omega_editJNI.omega_edit_destroy_viewport(SWIGTYPE_p_omega_viewport_t.getCPtr(viewport_ptr));
  }

  public static int omega_edit_clear_changes(SWIGTYPE_p_omega_session_t session_ptr) {
    return omega_editJNI.omega_edit_clear_changes(SWIGTYPE_p_omega_session_t.getCPtr(session_ptr));
  }

  public static long omega_edit_undo_last_change(SWIGTYPE_p_omega_session_t session_ptr) {
    return omega_editJNI.omega_edit_undo_last_change(SWIGTYPE_p_omega_session_t.getCPtr(session_ptr));
  }

  public static long omega_edit_redo_last_undo(SWIGTYPE_p_omega_session_t session_ptr) {
    return omega_editJNI.omega_edit_redo_last_undo(SWIGTYPE_p_omega_session_t.getCPtr(session_ptr));
  }

  public static int omega_edit_save(SWIGTYPE_p_omega_session_t session_ptr, String file_path, int overwrite) {
    return omega_editJNI.omega_edit_save(SWIGTYPE_p_omega_session_t.getCPtr(session_ptr), file_path, overwrite);
  }

  public static long omega_edit_delete(SWIGTYPE_p_omega_session_t session_ptr, long offset, long length) {
    return omega_editJNI.omega_edit_delete(SWIGTYPE_p_omega_session_t.getCPtr(session_ptr), offset, length);
  }

  public static long omega_edit_insert_bytes(SWIGTYPE_p_omega_session_t session_ptr, long offset, SWIGTYPE_p_omega_byte_t bytes, long length) {
    return omega_editJNI.omega_edit_insert_bytes(SWIGTYPE_p_omega_session_t.getCPtr(session_ptr), offset, SWIGTYPE_p_omega_byte_t.getCPtr(bytes), length);
  }

  public static long omega_edit_insert(SWIGTYPE_p_omega_session_t session_ptr, long offset, String cstr, long length) {
    return omega_editJNI.omega_edit_insert(SWIGTYPE_p_omega_session_t.getCPtr(session_ptr), offset, cstr, length);
  }

  public static long omega_edit_overwrite_bytes(SWIGTYPE_p_omega_session_t session_ptr, long offset, SWIGTYPE_p_omega_byte_t bytes, long length) {
    return omega_editJNI.omega_edit_overwrite_bytes(SWIGTYPE_p_omega_session_t.getCPtr(session_ptr), offset, SWIGTYPE_p_omega_byte_t.getCPtr(bytes), length);
  }

  public static long omega_edit_overwrite(SWIGTYPE_p_omega_session_t session_ptr, long offset, String cstr, long length) {
    return omega_editJNI.omega_edit_overwrite(SWIGTYPE_p_omega_session_t.getCPtr(session_ptr), offset, cstr, length);
  }

  public static String omega_license_get() {
    return omega_editJNI.omega_license_get();
  }

  public static SWIGTYPE_p_omega_search_context_t omega_search_create_context_bytes(SWIGTYPE_p_omega_session_t session_ptr, SWIGTYPE_p_omega_byte_t pattern, long pattern_length, long session_offset, long session_length, int case_insensitive) {
    long cPtr = omega_editJNI.omega_search_create_context_bytes(SWIGTYPE_p_omega_session_t.getCPtr(session_ptr), SWIGTYPE_p_omega_byte_t.getCPtr(pattern), pattern_length, session_offset, session_length, case_insensitive);
    return (cPtr == 0) ? null : new SWIGTYPE_p_omega_search_context_t(cPtr, false);
  }

  public static SWIGTYPE_p_omega_search_context_t omega_search_create_context(SWIGTYPE_p_omega_session_t session_ptr, String pattern, long pattern_length, long session_offset, long session_length, int case_insensitive) {
    long cPtr = omega_editJNI.omega_search_create_context(SWIGTYPE_p_omega_session_t.getCPtr(session_ptr), pattern, pattern_length, session_offset, session_length, case_insensitive);
    return (cPtr == 0) ? null : new SWIGTYPE_p_omega_search_context_t(cPtr, false);
  }

  public static long omega_search_context_get_offset(SWIGTYPE_p_omega_search_context_t search_context_ptr) {
    return omega_editJNI.omega_search_context_get_offset(SWIGTYPE_p_omega_search_context_t.getCPtr(search_context_ptr));
  }

  public static long omega_search_context_get_length(SWIGTYPE_p_omega_search_context_t search_context_ptr) {
    return omega_editJNI.omega_search_context_get_length(SWIGTYPE_p_omega_search_context_t.getCPtr(search_context_ptr));
  }

  public static int omega_search_next_match(SWIGTYPE_p_omega_search_context_t search_context_ptr, long advance_context) {
    return omega_editJNI.omega_search_next_match(SWIGTYPE_p_omega_search_context_t.getCPtr(search_context_ptr), advance_context);
  }

  public static void omega_search_destroy_context(SWIGTYPE_p_omega_search_context_t search_context_ptr) {
    omega_editJNI.omega_search_destroy_context(SWIGTYPE_p_omega_search_context_t.getCPtr(search_context_ptr));
  }

  public static String omega_session_get_file_path(SWIGTYPE_p_omega_session_t session_ptr) {
    return omega_editJNI.omega_session_get_file_path(SWIGTYPE_p_omega_session_t.getCPtr(session_ptr));
  }

  public static SWIGTYPE_p_void omega_session_get_user_data(SWIGTYPE_p_omega_session_t session_ptr) {
    long cPtr = omega_editJNI.omega_session_get_user_data(SWIGTYPE_p_omega_session_t.getCPtr(session_ptr));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static long omega_session_get_num_viewports(SWIGTYPE_p_omega_session_t session_ptr) {
    return omega_editJNI.omega_session_get_num_viewports(SWIGTYPE_p_omega_session_t.getCPtr(session_ptr));
  }

  public static long omega_session_get_num_changes(SWIGTYPE_p_omega_session_t session_ptr) {
    return omega_editJNI.omega_session_get_num_changes(SWIGTYPE_p_omega_session_t.getCPtr(session_ptr));
  }

  public static long omega_session_get_num_undone_changes(SWIGTYPE_p_omega_session_t session_ptr) {
    return omega_editJNI.omega_session_get_num_undone_changes(SWIGTYPE_p_omega_session_t.getCPtr(session_ptr));
  }

  public static long omega_session_get_computed_file_size(SWIGTYPE_p_omega_session_t session_ptr) {
    return omega_editJNI.omega_session_get_computed_file_size(SWIGTYPE_p_omega_session_t.getCPtr(session_ptr));
  }

  public static SWIGTYPE_p_omega_change_t omega_session_get_last_change(SWIGTYPE_p_omega_session_t session_ptr) {
    long cPtr = omega_editJNI.omega_session_get_last_change(SWIGTYPE_p_omega_session_t.getCPtr(session_ptr));
    return (cPtr == 0) ? null : new SWIGTYPE_p_omega_change_t(cPtr, false);
  }

  public static SWIGTYPE_p_omega_change_t omega_session_get_last_undo(SWIGTYPE_p_omega_session_t session_ptr) {
    long cPtr = omega_editJNI.omega_session_get_last_undo(SWIGTYPE_p_omega_session_t.getCPtr(session_ptr));
    return (cPtr == 0) ? null : new SWIGTYPE_p_omega_change_t(cPtr, false);
  }

  public static SWIGTYPE_p_omega_change_t omega_session_get_change(SWIGTYPE_p_omega_session_t session_ptr, long change_serial) {
    long cPtr = omega_editJNI.omega_session_get_change(SWIGTYPE_p_omega_session_t.getCPtr(session_ptr), change_serial);
    return (cPtr == 0) ? null : new SWIGTYPE_p_omega_change_t(cPtr, false);
  }

  public static int omega_session_viewport_on_change_callbacks_paused(SWIGTYPE_p_omega_session_t session_ptr) {
    return omega_editJNI.omega_session_viewport_on_change_callbacks_paused(SWIGTYPE_p_omega_session_t.getCPtr(session_ptr));
  }

  public static void omega_session_pause_viewport_on_change_callbacks(SWIGTYPE_p_omega_session_t session_ptr) {
    omega_editJNI.omega_session_pause_viewport_on_change_callbacks(SWIGTYPE_p_omega_session_t.getCPtr(session_ptr));
  }

  public static void omega_session_resume_viewport_on_change_callbacks(SWIGTYPE_p_omega_session_t session_ptr) {
    omega_editJNI.omega_session_resume_viewport_on_change_callbacks(SWIGTYPE_p_omega_session_t.getCPtr(session_ptr));
  }

  public static String omega_change_get_string(SWIGTYPE_p_omega_change_t change_ptr) {
    return omega_editJNI.omega_change_get_string(SWIGTYPE_p_omega_change_t.getCPtr(change_ptr));
  }

  public static String omega_viewport_get_string(SWIGTYPE_p_omega_viewport_t viewport_ptr) {
    return omega_editJNI.omega_viewport_get_string(SWIGTYPE_p_omega_viewport_t.getCPtr(viewport_ptr));
  }

  public static long omega_edit_insert_string(SWIGTYPE_p_omega_session_t session_ptr, long offset, String str) {
    return omega_editJNI.omega_edit_insert_string(SWIGTYPE_p_omega_session_t.getCPtr(session_ptr), offset, str);
  }

  public static long omega_edit_overwrite_string(SWIGTYPE_p_omega_session_t session_ptr, long offset, String str) {
    return omega_editJNI.omega_edit_overwrite_string(SWIGTYPE_p_omega_session_t.getCPtr(session_ptr), offset, str);
  }

  public static SWIGTYPE_p_omega_search_context_t omega_search_create_context_string(SWIGTYPE_p_omega_session_t session_ptr, String pattern, long session_offset, long session_length, int case_insensitive) {
    long cPtr = omega_editJNI.omega_search_create_context_string__SWIG_0(SWIGTYPE_p_omega_session_t.getCPtr(session_ptr), pattern, session_offset, session_length, case_insensitive);
    return (cPtr == 0) ? null : new SWIGTYPE_p_omega_search_context_t(cPtr, false);
  }

  public static SWIGTYPE_p_omega_search_context_t omega_search_create_context_string(SWIGTYPE_p_omega_session_t session_ptr, String pattern, long session_offset, long session_length) {
    long cPtr = omega_editJNI.omega_search_create_context_string__SWIG_1(SWIGTYPE_p_omega_session_t.getCPtr(session_ptr), pattern, session_offset, session_length);
    return (cPtr == 0) ? null : new SWIGTYPE_p_omega_search_context_t(cPtr, false);
  }

  public static SWIGTYPE_p_omega_search_context_t omega_search_create_context_string(SWIGTYPE_p_omega_session_t session_ptr, String pattern, long session_offset) {
    long cPtr = omega_editJNI.omega_search_create_context_string__SWIG_2(SWIGTYPE_p_omega_session_t.getCPtr(session_ptr), pattern, session_offset);
    return (cPtr == 0) ? null : new SWIGTYPE_p_omega_search_context_t(cPtr, false);
  }

  public static SWIGTYPE_p_omega_search_context_t omega_search_create_context_string(SWIGTYPE_p_omega_session_t session_ptr, String pattern) {
    long cPtr = omega_editJNI.omega_search_create_context_string__SWIG_3(SWIGTYPE_p_omega_session_t.getCPtr(session_ptr), pattern);
    return (cPtr == 0) ? null : new SWIGTYPE_p_omega_search_context_t(cPtr, false);
  }

  public static int omega_version_major() {
    return omega_editJNI.omega_version_major();
  }

  public static int omega_version_minor() {
    return omega_editJNI.omega_version_minor();
  }

  public static int omega_version_patch() {
    return omega_editJNI.omega_version_patch();
  }

  public static int omega_version() {
    return omega_editJNI.omega_version();
  }

  public static SWIGTYPE_p_omega_session_t omega_viewport_get_session(SWIGTYPE_p_omega_viewport_t viewport_ptr) {
    long cPtr = omega_editJNI.omega_viewport_get_session(SWIGTYPE_p_omega_viewport_t.getCPtr(viewport_ptr));
    return (cPtr == 0) ? null : new SWIGTYPE_p_omega_session_t(cPtr, false);
  }

  public static long omega_viewport_get_capacity(SWIGTYPE_p_omega_viewport_t viewport_ptr) {
    return omega_editJNI.omega_viewport_get_capacity(SWIGTYPE_p_omega_viewport_t.getCPtr(viewport_ptr));
  }

  public static long omega_viewport_get_length(SWIGTYPE_p_omega_viewport_t viewport_ptr) {
    return omega_editJNI.omega_viewport_get_length(SWIGTYPE_p_omega_viewport_t.getCPtr(viewport_ptr));
  }

  public static SWIGTYPE_p_omega_byte_t omega_viewport_get_data(SWIGTYPE_p_omega_viewport_t viewport_ptr) {
    long cPtr = omega_editJNI.omega_viewport_get_data(SWIGTYPE_p_omega_viewport_t.getCPtr(viewport_ptr));
    return (cPtr == 0) ? null : new SWIGTYPE_p_omega_byte_t(cPtr, false);
  }

  public static int omega_viewport_has_changes(SWIGTYPE_p_omega_viewport_t viewport_ptr) {
    return omega_editJNI.omega_viewport_has_changes(SWIGTYPE_p_omega_viewport_t.getCPtr(viewport_ptr));
  }

  public static long omega_viewport_get_offset(SWIGTYPE_p_omega_viewport_t viewport_ptr) {
    return omega_editJNI.omega_viewport_get_offset(SWIGTYPE_p_omega_viewport_t.getCPtr(viewport_ptr));
  }

  public static SWIGTYPE_p_void omega_viewport_get_user_data(SWIGTYPE_p_omega_viewport_t viewport_ptr) {
    long cPtr = omega_editJNI.omega_viewport_get_user_data(SWIGTYPE_p_omega_viewport_t.getCPtr(viewport_ptr));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static int omega_viewport_update(SWIGTYPE_p_omega_viewport_t viewport_ptr, long offset, long capacity) {
    return omega_editJNI.omega_viewport_update(SWIGTYPE_p_omega_viewport_t.getCPtr(viewport_ptr), offset, capacity);
  }

  public static void omega_viewport_execute_on_change(SWIGTYPE_p_omega_viewport_t viewport_ptr, SWIGTYPE_p_omega_change_t change_ptr) {
    omega_editJNI.omega_viewport_execute_on_change(SWIGTYPE_p_omega_viewport_t.getCPtr(viewport_ptr), SWIGTYPE_p_omega_change_t.getCPtr(change_ptr));
  }

  public static int omega_visit_changes(SWIGTYPE_p_omega_session_t session_ptr, SWIGTYPE_p_f_p_q_const__omega_change_t_p_void__int cbk, SWIGTYPE_p_void user_data) {
    return omega_editJNI.omega_visit_changes(SWIGTYPE_p_omega_session_t.getCPtr(session_ptr), SWIGTYPE_p_f_p_q_const__omega_change_t_p_void__int.getCPtr(cbk), SWIGTYPE_p_void.getCPtr(user_data));
  }

  public static int omega_visit_changes_reverse(SWIGTYPE_p_omega_session_t session_ptr, SWIGTYPE_p_f_p_q_const__omega_change_t_p_void__int cbk, SWIGTYPE_p_void user_data) {
    return omega_editJNI.omega_visit_changes_reverse(SWIGTYPE_p_omega_session_t.getCPtr(session_ptr), SWIGTYPE_p_f_p_q_const__omega_change_t_p_void__int.getCPtr(cbk), SWIGTYPE_p_void.getCPtr(user_data));
  }

  public static SWIGTYPE_p_omega_visit_change_context_struct omega_visit_change_create_context(SWIGTYPE_p_omega_session_t session_ptr, int reverse) {
    long cPtr = omega_editJNI.omega_visit_change_create_context(SWIGTYPE_p_omega_session_t.getCPtr(session_ptr), reverse);
    return (cPtr == 0) ? null : new SWIGTYPE_p_omega_visit_change_context_struct(cPtr, false);
  }

  public static int omega_visit_change_next(SWIGTYPE_p_omega_visit_change_context_struct change_context_ptr) {
    return omega_editJNI.omega_visit_change_next(SWIGTYPE_p_omega_visit_change_context_struct.getCPtr(change_context_ptr));
  }

  public static SWIGTYPE_p_omega_change_t omega_visit_change_context_get_change(SWIGTYPE_p_omega_visit_change_context_struct change_context_ptr) {
    long cPtr = omega_editJNI.omega_visit_change_context_get_change(SWIGTYPE_p_omega_visit_change_context_struct.getCPtr(change_context_ptr));
    return (cPtr == 0) ? null : new SWIGTYPE_p_omega_change_t(cPtr, false);
  }

  public static void omega_visit_change_destroy_context(SWIGTYPE_p_omega_visit_change_context_struct change_context_ptr) {
    omega_editJNI.omega_visit_change_destroy_context(SWIGTYPE_p_omega_visit_change_context_struct.getCPtr(change_context_ptr));
  }

}
