/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class OmegaViewportOnChangeDirector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OmegaViewportOnChangeDirector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OmegaViewportOnChangeDirector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        omega_editJNI.delete_OmegaViewportOnChangeDirector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    omega_editJNI.OmegaViewportOnChangeDirector_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    omega_editJNI.OmegaViewportOnChangeDirector_change_ownership(this, swigCPtr, true);
  }

  public void handle_viewport_change(SWIGTYPE_p_omega_viewport_t arg0, SWIGTYPE_p_omega_change_t arg1) {
    omega_editJNI.OmegaViewportOnChangeDirector_handle_viewport_change(swigCPtr, this, SWIGTYPE_p_omega_viewport_t.getCPtr(arg0), SWIGTYPE_p_omega_change_t.getCPtr(arg1));
  }

  public OmegaViewportOnChangeDirector() {
    this(omega_editJNI.new_OmegaViewportOnChangeDirector(), true);
    omega_editJNI.OmegaViewportOnChangeDirector_director_connect(this, swigCPtr, true, true);
  }

}
