/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface omega_editConstants {
  public final static int OMEGA_VIEWPORT_CAPACITY_LIMIT = omega_editJNI.OMEGA_VIEWPORT_CAPACITY_LIMIT_get();
  public final static int OMEGA_SEARCH_PATTERN_LENGTH_LIMIT = omega_editJNI.OMEGA_SEARCH_PATTERN_LENGTH_LIMIT_get();
}
