/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class SWIGTYPE_p_omega_visit_change_context_struct {
  private transient long swigCPtr;

  protected SWIGTYPE_p_omega_visit_change_context_struct(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_omega_visit_change_context_struct() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_omega_visit_change_context_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

