# Copyright (c) 2021-2022 Concurrent Technologies Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software is distributed under the License is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.  See the License for the specific language governing permissions and limitations under the License.

# for full syntax documentation see:  https://lgtm.com/help/lgtm/lgtm.yml-configuration-file

path_classifiers:
  test:
    - "*/src/rpc/tests/**/*"
    - "*/src/tests/**/*"
    - "*/src/examples/**/*"
extraction:
  cpp:
    prepare:
      packages:
        - g++-10
        - ccache
      script:
        - mkdir -p ~/.conan
        - cat /usr/local/share/ca-certificates/semmle-cache-ca/semmle-cache-ca.crt >> ~/.conan/cacert.pem
        - python3 -m pip install --upgrade pip setuptools
        - python3 -m pip install cmake conan
        - source ~/.profile
    configure:
      command:
        - mkdir -p build
        - cmake -D OPT_ENABLE_COVERAGE:BOOL=TRUE -D CMAKE_BUILD_TYPE:STRING=Debug -D ENABLE_DEVELOPER_MODE:BOOL=FALSE  -S . -B build
    index:
      build_command: cmake --build ./build -- -j
