# Copyright (c) 2021 Concurrent Technologies Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software is distributed under the License is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.  See the License for the specific language governing permissions and limitations under the License.

# for full syntax documentation see:  https://lgtm.com/help/lgtm/lgtm.yml-configuration-file

path_classifiers:
  test:
    - "*/src/rpc/tests/**/*"
    - "*/src/tests/**/*"
    - "*/src/examples/**/*"
  docs:
    - "*/sphinx/**/*"

extraction:
  cpp:
    prepare:
      packages:
        - g++-10
        - ccache
        - python-pip
        - ca-certificates
    after_prepare:
      - pip3 install cmake conan --user --upgrade
      - ls ~/.local/bin
      - export PATH=$PATH:~/.local/bin
      - conan --version
      - conan profile new default --detect
      - cat /usr/local/share/ca-certificates/semmle-cache-ca/semmle-cache-ca.crt >> ~/.conan/cacert.pem
    configure:
      command:
        - cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DBUILD_DOCS=OFF
    index:
      build_command: cmake --build build
