# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Users/runner/work/_temp/504157251/cmake-3.22.2-macos-universal/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Users/runner/work/_temp/504157251/cmake-3.22.2-macos-universal/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/runner/work/omega-edit/omega-edit

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/runner/work/omega-edit/omega-edit/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/Users/runner/work/_temp/504157251/cmake-3.22.2-macos-universal/CMake.app/Contents/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/Users/runner/work/_temp/504157251/cmake-3.22.2-macos-universal/CMake.app/Contents/bin/cpack --config ./CPackSourceConfig.cmake /Users/runner/work/omega-edit/omega-edit/build/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Users/runner/work/_temp/504157251/cmake-3.22.2-macos-universal/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Users/runner/work/_temp/504157251/cmake-3.22.2-macos-universal/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"omega_edit_Development\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Users/runner/work/_temp/504157251/cmake-3.22.2-macos-universal/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Users/runner/work/_temp/504157251/cmake-3.22.2-macos-universal/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Users/runner/work/_temp/504157251/cmake-3.22.2-macos-universal/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Users/runner/work/_temp/504157251/cmake-3.22.2-macos-universal/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Users/runner/work/_temp/504157251/cmake-3.22.2-macos-universal/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Users/runner/work/_temp/504157251/cmake-3.22.2-macos-universal/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/runner/work/omega-edit/omega-edit/build/CMakeFiles /Users/runner/work/omega-edit/omega-edit/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/runner/work/omega-edit/omega-edit/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named omega_edit

# Build rule for target.
omega_edit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 omega_edit
.PHONY : omega_edit

# fast build rule for target.
omega_edit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/build
.PHONY : omega_edit/fast

src/lib/change.o: src/lib/change.cpp.o
.PHONY : src/lib/change.o

# target to build an object file
src/lib/change.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/change.cpp.o
.PHONY : src/lib/change.cpp.o

src/lib/change.i: src/lib/change.cpp.i
.PHONY : src/lib/change.i

# target to preprocess a source file
src/lib/change.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/change.cpp.i
.PHONY : src/lib/change.cpp.i

src/lib/change.s: src/lib/change.cpp.s
.PHONY : src/lib/change.s

# target to generate assembly for a file
src/lib/change.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/change.cpp.s
.PHONY : src/lib/change.cpp.s

src/lib/check.o: src/lib/check.cpp.o
.PHONY : src/lib/check.o

# target to build an object file
src/lib/check.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/check.cpp.o
.PHONY : src/lib/check.cpp.o

src/lib/check.i: src/lib/check.cpp.i
.PHONY : src/lib/check.i

# target to preprocess a source file
src/lib/check.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/check.cpp.i
.PHONY : src/lib/check.cpp.i

src/lib/check.s: src/lib/check.cpp.s
.PHONY : src/lib/check.s

# target to generate assembly for a file
src/lib/check.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/check.cpp.s
.PHONY : src/lib/check.cpp.s

src/lib/edit.o: src/lib/edit.cpp.o
.PHONY : src/lib/edit.o

# target to build an object file
src/lib/edit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/edit.cpp.o
.PHONY : src/lib/edit.cpp.o

src/lib/edit.i: src/lib/edit.cpp.i
.PHONY : src/lib/edit.i

# target to preprocess a source file
src/lib/edit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/edit.cpp.i
.PHONY : src/lib/edit.cpp.i

src/lib/edit.s: src/lib/edit.cpp.s
.PHONY : src/lib/edit.s

# target to generate assembly for a file
src/lib/edit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/edit.cpp.s
.PHONY : src/lib/edit.cpp.s

src/lib/encode.o: src/lib/encode.c.o
.PHONY : src/lib/encode.o

# target to build an object file
src/lib/encode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/encode.c.o
.PHONY : src/lib/encode.c.o

src/lib/encode.i: src/lib/encode.c.i
.PHONY : src/lib/encode.i

# target to preprocess a source file
src/lib/encode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/encode.c.i
.PHONY : src/lib/encode.c.i

src/lib/encode.s: src/lib/encode.c.s
.PHONY : src/lib/encode.s

# target to generate assembly for a file
src/lib/encode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/encode.c.s
.PHONY : src/lib/encode.c.s

src/lib/filesystem.o: src/lib/filesystem.cpp.o
.PHONY : src/lib/filesystem.o

# target to build an object file
src/lib/filesystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/filesystem.cpp.o
.PHONY : src/lib/filesystem.cpp.o

src/lib/filesystem.i: src/lib/filesystem.cpp.i
.PHONY : src/lib/filesystem.i

# target to preprocess a source file
src/lib/filesystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/filesystem.cpp.i
.PHONY : src/lib/filesystem.cpp.i

src/lib/filesystem.s: src/lib/filesystem.cpp.s
.PHONY : src/lib/filesystem.s

# target to generate assembly for a file
src/lib/filesystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/filesystem.cpp.s
.PHONY : src/lib/filesystem.cpp.s

src/lib/impl_/find.o: src/lib/impl_/find.cpp.o
.PHONY : src/lib/impl_/find.o

# target to build an object file
src/lib/impl_/find.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/impl_/find.cpp.o
.PHONY : src/lib/impl_/find.cpp.o

src/lib/impl_/find.i: src/lib/impl_/find.cpp.i
.PHONY : src/lib/impl_/find.i

# target to preprocess a source file
src/lib/impl_/find.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/impl_/find.cpp.i
.PHONY : src/lib/impl_/find.cpp.i

src/lib/impl_/find.s: src/lib/impl_/find.cpp.s
.PHONY : src/lib/impl_/find.s

# target to generate assembly for a file
src/lib/impl_/find.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/impl_/find.cpp.s
.PHONY : src/lib/impl_/find.cpp.s

src/lib/impl_/internal_fun.o: src/lib/impl_/internal_fun.cpp.o
.PHONY : src/lib/impl_/internal_fun.o

# target to build an object file
src/lib/impl_/internal_fun.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/impl_/internal_fun.cpp.o
.PHONY : src/lib/impl_/internal_fun.cpp.o

src/lib/impl_/internal_fun.i: src/lib/impl_/internal_fun.cpp.i
.PHONY : src/lib/impl_/internal_fun.i

# target to preprocess a source file
src/lib/impl_/internal_fun.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/impl_/internal_fun.cpp.i
.PHONY : src/lib/impl_/internal_fun.cpp.i

src/lib/impl_/internal_fun.s: src/lib/impl_/internal_fun.cpp.s
.PHONY : src/lib/impl_/internal_fun.s

# target to generate assembly for a file
src/lib/impl_/internal_fun.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/impl_/internal_fun.cpp.s
.PHONY : src/lib/impl_/internal_fun.cpp.s

src/lib/license.o: src/lib/license.c.o
.PHONY : src/lib/license.o

# target to build an object file
src/lib/license.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/license.c.o
.PHONY : src/lib/license.c.o

src/lib/license.i: src/lib/license.c.i
.PHONY : src/lib/license.i

# target to preprocess a source file
src/lib/license.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/license.c.i
.PHONY : src/lib/license.c.i

src/lib/license.s: src/lib/license.c.s
.PHONY : src/lib/license.s

# target to generate assembly for a file
src/lib/license.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/license.c.s
.PHONY : src/lib/license.c.s

src/lib/search.o: src/lib/search.cpp.o
.PHONY : src/lib/search.o

# target to build an object file
src/lib/search.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/search.cpp.o
.PHONY : src/lib/search.cpp.o

src/lib/search.i: src/lib/search.cpp.i
.PHONY : src/lib/search.i

# target to preprocess a source file
src/lib/search.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/search.cpp.i
.PHONY : src/lib/search.cpp.i

src/lib/search.s: src/lib/search.cpp.s
.PHONY : src/lib/search.s

# target to generate assembly for a file
src/lib/search.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/search.cpp.s
.PHONY : src/lib/search.cpp.s

src/lib/session.o: src/lib/session.cpp.o
.PHONY : src/lib/session.o

# target to build an object file
src/lib/session.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/session.cpp.o
.PHONY : src/lib/session.cpp.o

src/lib/session.i: src/lib/session.cpp.i
.PHONY : src/lib/session.i

# target to preprocess a source file
src/lib/session.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/session.cpp.i
.PHONY : src/lib/session.cpp.i

src/lib/session.s: src/lib/session.cpp.s
.PHONY : src/lib/session.s

# target to generate assembly for a file
src/lib/session.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/session.cpp.s
.PHONY : src/lib/session.cpp.s

src/lib/utility.o: src/lib/utility.c.o
.PHONY : src/lib/utility.o

# target to build an object file
src/lib/utility.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/utility.c.o
.PHONY : src/lib/utility.c.o

src/lib/utility.i: src/lib/utility.c.i
.PHONY : src/lib/utility.i

# target to preprocess a source file
src/lib/utility.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/utility.c.i
.PHONY : src/lib/utility.c.i

src/lib/utility.s: src/lib/utility.c.s
.PHONY : src/lib/utility.s

# target to generate assembly for a file
src/lib/utility.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/utility.c.s
.PHONY : src/lib/utility.c.s

src/lib/version.o: src/lib/version.c.o
.PHONY : src/lib/version.o

# target to build an object file
src/lib/version.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/version.c.o
.PHONY : src/lib/version.c.o

src/lib/version.i: src/lib/version.c.i
.PHONY : src/lib/version.i

# target to preprocess a source file
src/lib/version.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/version.c.i
.PHONY : src/lib/version.c.i

src/lib/version.s: src/lib/version.c.s
.PHONY : src/lib/version.s

# target to generate assembly for a file
src/lib/version.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/version.c.s
.PHONY : src/lib/version.c.s

src/lib/viewport.o: src/lib/viewport.cpp.o
.PHONY : src/lib/viewport.o

# target to build an object file
src/lib/viewport.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/viewport.cpp.o
.PHONY : src/lib/viewport.cpp.o

src/lib/viewport.i: src/lib/viewport.cpp.i
.PHONY : src/lib/viewport.i

# target to preprocess a source file
src/lib/viewport.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/viewport.cpp.i
.PHONY : src/lib/viewport.cpp.i

src/lib/viewport.s: src/lib/viewport.cpp.s
.PHONY : src/lib/viewport.s

# target to generate assembly for a file
src/lib/viewport.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/viewport.cpp.s
.PHONY : src/lib/viewport.cpp.s

src/lib/visit.o: src/lib/visit.cpp.o
.PHONY : src/lib/visit.o

# target to build an object file
src/lib/visit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/visit.cpp.o
.PHONY : src/lib/visit.cpp.o

src/lib/visit.i: src/lib/visit.cpp.i
.PHONY : src/lib/visit.i

# target to preprocess a source file
src/lib/visit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/visit.cpp.i
.PHONY : src/lib/visit.cpp.i

src/lib/visit.s: src/lib/visit.cpp.s
.PHONY : src/lib/visit.s

# target to generate assembly for a file
src/lib/visit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omega_edit.dir/build.make CMakeFiles/omega_edit.dir/src/lib/visit.cpp.s
.PHONY : src/lib/visit.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... omega_edit"
	@echo "... src/lib/change.o"
	@echo "... src/lib/change.i"
	@echo "... src/lib/change.s"
	@echo "... src/lib/check.o"
	@echo "... src/lib/check.i"
	@echo "... src/lib/check.s"
	@echo "... src/lib/edit.o"
	@echo "... src/lib/edit.i"
	@echo "... src/lib/edit.s"
	@echo "... src/lib/encode.o"
	@echo "... src/lib/encode.i"
	@echo "... src/lib/encode.s"
	@echo "... src/lib/filesystem.o"
	@echo "... src/lib/filesystem.i"
	@echo "... src/lib/filesystem.s"
	@echo "... src/lib/impl_/find.o"
	@echo "... src/lib/impl_/find.i"
	@echo "... src/lib/impl_/find.s"
	@echo "... src/lib/impl_/internal_fun.o"
	@echo "... src/lib/impl_/internal_fun.i"
	@echo "... src/lib/impl_/internal_fun.s"
	@echo "... src/lib/license.o"
	@echo "... src/lib/license.i"
	@echo "... src/lib/license.s"
	@echo "... src/lib/search.o"
	@echo "... src/lib/search.i"
	@echo "... src/lib/search.s"
	@echo "... src/lib/session.o"
	@echo "... src/lib/session.i"
	@echo "... src/lib/session.s"
	@echo "... src/lib/utility.o"
	@echo "... src/lib/utility.i"
	@echo "... src/lib/utility.s"
	@echo "... src/lib/version.o"
	@echo "... src/lib/version.i"
	@echo "... src/lib/version.s"
	@echo "... src/lib/viewport.o"
	@echo "... src/lib/viewport.i"
	@echo "... src/lib/viewport.s"
	@echo "... src/lib/visit.o"
	@echo "... src/lib/visit.i"
	@echo "... src/lib/visit.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

