#!/bin/bash

function cmake-build {
    cmake -S . -B cmake-build
}

function cmake-debug {
    cmake -S . -B cmake-build \
        -DCMAKE_BUILD_TYPE=Debug -DCMAKE_DEPENDS_USE_COMPILER=FALSE \
        -G "CodeBlocks - Unix Makefiles" .
}

function cmake-test {
    cmake-build
    cmake --build cmake-build --target omega_test -- -j 6
    pushd .
    cd cmake-build/src/tests/
    ./omega_test -d yes --order lex
    popd
}

function swig-compile {
    swig -javascript -node -v -c++ src/bindings/omega_edit.i
}

function gyp-configure {
    yarn run gyp-configure
}

function gyp-build {
    gyp-configure
    yarn run gyp-build
}

function transpile {
  mkdir -p build-em
  pushd .
  cd build-em
  emcmake cmake ..
  make
  popd
}

$@
