#!/bin/bash

function cmake-build {
    cmake -S . -B cmake-build
}

function cmake-debug {
    cmake -S . -B cmake-build \
        -DCMAKE_BUILD_TYPE=Debug -DCMAKE_DEPENDS_USE_COMPILER=FALSE \
        -G "CodeBlocks - Unix Makefiles" .
}

function cmake-test {
    cmake-build
    cmake --build cmake-build --target omega_test -- -j 6
    pushd .
    # shellcheck disable=SC2164
    cd cmake-build/src/tests/
    ./omega_test -d yes --order lex
    # shellcheck disable=SC2164
    popd
}

function swig-compile {
    swig -javascript -node -v -c++ src/bindings/omega_edit.i
}

function gyp-configure {
    yarn run gyp-configure
}

function gyp-build {
    gyp-configure
    yarn run gyp-build
}

function gyp-rebuild {
    yarn run gyp-rebuild
}

# shellcheck disable=SC2068
$@
