/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {
  CountKind,
  CountRequest,
  CreateViewportRequest,
  ObjectId,
  ViewportDataRequest,
  ViewportDataResponse,
} from './omega_edit_pb'
import { ALL_EVENTS, getClient } from './settings'

/**
 * Create a new viewport in a session
 * @param desired_viewport_id if defined, the viewport ID to assign to this viewport, if undefined a unique viewport ID
 * will be generated by the server
 * @param session_id session to create the viewport in
 * @param offset byte-offset start of the viewport
 * @param capacity capacity of the viewport in bytes
 * @param is_floating false if the viewport is to remain fixed at the given offset, true if the viewport is expected to
 * "float" as bytes are inserted or deleted before the start of this viewport
 * @return created viewport's ID, on success
 */
export function createViewport(
  desired_viewport_id: string | undefined,
  session_id: string,
  offset: number,
  capacity: number,
  is_floating: boolean
): Promise<string> {
  return new Promise<string>((resolve, reject) => {
    let request = new CreateViewportRequest()
    if (desired_viewport_id) request.setViewportIdDesired(desired_viewport_id)
    request.setSessionId(session_id)
    request.setOffset(offset)
    request.setCapacity(capacity)
    request.setIsFloating(is_floating)
    request.setEventInterest(ALL_EVENTS)
    getClient().createViewport(request, (err, r) => {
      if (err) {
        console.log(err.message)
        return reject('createViewport error: ' + err.message)
      }
      return resolve(r.getViewportId())
    })
  })
}

/**
 * Destroy a given viewport
 * @param viewport_id viewport to destroy
 * @return destroyed viewport's ID, on success
 */
export function destroyViewport(viewport_id: string): Promise<string> {
  return new Promise<string>((resolve, reject) => {
    getClient().destroyViewport(new ObjectId().setId(viewport_id), (err, r) => {
      if (err) {
        return reject('deleteViewport error: ' + err.message)
      }
      return resolve(r.getId())
    })
  })
}

/**
 * Given a session, return the number of viewports in that session
 * @param sesssion_id session to get the number of viewports in
 * @return number of viewports in the given session, on success
 */
export function getViewportCount(sesssion_id: string): Promise<number> {
  return new Promise<number>((resolve, reject) => {
    getClient().getCount(
      new CountRequest()
        .setSessionId(sesssion_id)
        .setKind(CountKind.COUNT_VIEWPORTS),
      (err, r) => {
        if (err) {
          console.log(err.message)
          return reject('redo error: ' + err.message)
        }
        return resolve(r.getCount())
      }
    )
  })
}

/**
 * Given a viewport ID, return the data in the viewport
 * @param viewport_id viewport to get the data from
 * @return ViewportDataResponse with the data and where it is in the session, on success
 * @remarks viewport length can be less than the viewport capacity
 */
export function getViewportData(
  viewport_id: string
): Promise<ViewportDataResponse> {
  return new Promise<ViewportDataResponse>((resolve, reject) => {
    getClient().getViewportData(
      new ViewportDataRequest().setViewportId(viewport_id),
      (err, r) => {
        if (err) {
          console.log(err.message)
          return reject('redo error: ' + err.message)
        }
        return resolve(r)
      }
    )
  })
}

/**
 * Pause events being triggered on this viewport
 * @param viewport_id viewport to pause events on
 * @return viewport ID that has had its events paused, on success
 */
export function pauseViewportEvents(viewport_id: string): Promise<string> {
  return new Promise<string>((resolve, reject) => {
    getClient().pauseViewportEvents(
      new ObjectId().setId(viewport_id),
      (err, r) => {
        if (err) {
          console.log(err.message)
          return reject('pauseViewportEvents error: ' + err.message)
        }
        return resolve(r.getId())
      }
    )
  })
}

/**
 * Resume events on the given viewport
 * @param viewport_id viewport to resume events on
 * @return viewport ID that has had its events resumed, on success
 */
export function resumeViewportEvents(viewport_id: string): Promise<string> {
  return new Promise<string>((resolve, reject) => {
    getClient().resumeViewportEvents(
      new ObjectId().setId(viewport_id),
      (err, r) => {
        if (err) {
          console.log(err.message)
          return reject('resumeViewportEvents error: ' + err.message)
        }
        return resolve(r.getId())
      }
    )
  })
}

/**
 * Unsubscribe from events for the given viewport
 * @param viewport_id viewport to unsubscribe from events
 * @return viewport ID that has been unsubscribed from events, on success
 */
export function unsubscribeViewport(viewport_id: string): Promise<string> {
  return new Promise<string>((resolve, reject) => {
    getClient().unsubscribeToViewportEvents(
      new ObjectId().setId(viewport_id),
      (err, r) => {
        if (err) {
          console.log(err.message)
          return reject('viewportUnsubscribe error: ' + err.message)
        }
        return resolve(r.getId())
      }
    )
  })
}
