.TH "src/include/omega_edit Directory Reference" 3 "Wed Mar 2 2022" "Version 0.8.1" "omega_edit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/omega_edit Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbyte\&.h\fP"
.br
.ti -1c
.RI "file \fBchange\&.h\fP"
.br
.ti -1c
.RI "file \fBcheck\&.h\fP"
.br
.ti -1c
.RI "file \fBconfig\&.h\fP"
.br
.ti -1c
.RI "file \fBedit\&.h\fP"
.br
.ti -1c
.RI "file \fBencode\&.h\fP"
.br
.ti -1c
.RI "file \fBexport\&.h\fP"
.br
.ti -1c
.RI "file \fBfilesystem\&.h\fP"
.br
.ti -1c
.RI "file \fBfwd_defs\&.h\fP"
.br
.ti -1c
.RI "file \fBlicense\&.h\fP"
.br
.ti -1c
.RI "file \fBscoped_ptr\&.hpp\fP"
.br
.ti -1c
.RI "file \fBsearch\&.h\fP"
.br
.ti -1c
.RI "file \fBsession\&.h\fP"
.br
.ti -1c
.RI "file \fBstl_string_adaptor\&.hpp\fP"
.br
.ti -1c
.RI "file \fButility\&.h\fP"
.br
.ti -1c
.RI "file \fBversion\&.h\fP"
.br
.ti -1c
.RI "file \fBviewport\&.h\fP"
.br
.ti -1c
.RI "file \fBvisit\&.h\fP"
.br
.in -1c
