.TH "src/include Directory Reference" 3 "Thu Mar 3 2022" "Version 0.8.1" "omega_edit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBomega_edit\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBomega_edit\&.h\fP"
.br
.in -1c
