.TH "src/include/omega_edit/byte.h" 3 "Wed Mar 2 2022" "Version 0.8.1" "omega_edit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/omega_edit/byte.h
.SH SYNOPSIS
.br
.PP
\fC#include 'config\&.h'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBOMEGA_BYTE_T\fP \fBomega_byte_t\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBOMEGA_BYTE_T\fP \fBomega_byte_t\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for omega_edit from the source code\&.
