.TH "src/include/omega_edit/check.h" 3 "Wed Mar 2 2022" "Version 0.8.1" "omega_edit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/omega_edit/check.h
.SH SYNOPSIS
.br
.PP
\fC#include 'export\&.h'\fP
.br
\fC#include 'fwd_defs\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBOMEGA_EDIT_EXPORT\fP int \fBomega_check_model\fP (const \fBomega_session_t\fP *session_ptr)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBOMEGA_EDIT_EXPORT\fP int omega_check_model (const \fBomega_session_t\fP * session_ptr)"
Checks the internal session model for errors 
.PP
\fBParameters\fP
.RS 4
\fIsession_ptr\fP session whose model to check for errors 
.RE
.PP
\fBReturns\fP
.RS 4
0 if the model is error free and non-zero otherwise 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for omega_edit from the source code\&.
