.TH "src/include/omega_edit/config.h" 3 "Thu Mar 3 2022" "Version 0.8.1" "omega_edit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/omega_edit/config.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOMEGA_VIEWPORT_CAPACITY_LIMIT\fP   (1024 * 1024)"
.br
.ti -1c
.RI "#define \fBOMEGA_SEARCH_PATTERN_LENGTH_LIMIT\fP   (\fBOMEGA_VIEWPORT_CAPACITY_LIMIT\fP / 2)"
.br
.ti -1c
.RI "#define \fBOMEGA_BYTE_T\fP   unsigned char"
.br
.ti -1c
.RI "#define \fBOMEGA_BUILD_UNIX\fP"
.br
.ti -1c
.RI "#define \fBOMEGA_BUILD_64_BIT\fP"
.br
.ti -1c
.RI "#define \fBOPEN\fP   open"
.br
.ti -1c
.RI "#define \fBFSEEK\fP   fseek"
.br
.ti -1c
.RI "#define \fBFTELL\fP   ftell"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FSEEK   fseek"

.SS "#define FTELL   ftell"

.SS "#define OMEGA_BUILD_64_BIT"

.SS "#define OMEGA_BUILD_UNIX"

.SS "#define OMEGA_BYTE_T   unsigned char"

.SS "#define OMEGA_SEARCH_PATTERN_LENGTH_LIMIT   (\fBOMEGA_VIEWPORT_CAPACITY_LIMIT\fP / 2)"

.SS "#define OMEGA_VIEWPORT_CAPACITY_LIMIT   (1024 * 1024)"

.SS "#define OPEN   open"

.SH "Author"
.PP 
Generated automatically by Doxygen for omega_edit from the source code\&.
