.TH "src/include/omega_edit/export.h" 3 "Wed Mar 2 2022" "Version 0.8.1" "omega_edit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/omega_edit/export.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOMEGA_EDIT_EXPORT\fP"
.br
.ti -1c
.RI "#define \fBOMEGA_EDIT_NO_EXPORT\fP"
.br
.ti -1c
.RI "#define \fBOMEGA_EDIT_DEPRECATED\fP   __attribute__ ((__deprecated__))"
.br
.ti -1c
.RI "#define \fBOMEGA_EDIT_DEPRECATED_EXPORT\fP   \fBOMEGA_EDIT_EXPORT\fP \fBOMEGA_EDIT_DEPRECATED\fP"
.br
.ti -1c
.RI "#define \fBOMEGA_EDIT_DEPRECATED_NO_EXPORT\fP   \fBOMEGA_EDIT_NO_EXPORT\fP \fBOMEGA_EDIT_DEPRECATED\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define OMEGA_EDIT_DEPRECATED   __attribute__ ((__deprecated__))"

.SS "#define OMEGA_EDIT_DEPRECATED_EXPORT   \fBOMEGA_EDIT_EXPORT\fP \fBOMEGA_EDIT_DEPRECATED\fP"

.SS "#define OMEGA_EDIT_DEPRECATED_NO_EXPORT   \fBOMEGA_EDIT_NO_EXPORT\fP \fBOMEGA_EDIT_DEPRECATED\fP"

.SS "#define OMEGA_EDIT_EXPORT"

.SS "#define OMEGA_EDIT_NO_EXPORT"

.SH "Author"
.PP 
Generated automatically by Doxygen for omega_edit from the source code\&.
