.TH "src/include/omega_edit/fwd_defs.h" 3 "Wed Mar 2 2022" "Version 0.8.1" "omega_edit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/omega_edit/fwd_defs.h
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct omega_session_struct \fBomega_session_t\fP"
.br
.ti -1c
.RI "typedef struct omega_change_struct \fBomega_change_t\fP"
.br
.ti -1c
.RI "typedef struct omega_viewport_struct \fBomega_viewport_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBomega_session_event_t\fP { \fBSESSION_EVT_UNDEFINED\fP = 0, \fBSESSION_EVT_CREATE\fP = 1, \fBSESSION_EVT_EDIT\fP = 2, \fBSESSION_EVT_UNDO\fP = 4, \fBSESSION_EVT_CLEAR\fP = 8, \fBSESSION_EVT_TRANSFORM\fP = 16, \fBSESSION_EVT_CREATE_CHECKPOINT\fP = 32, \fBSESSION_EVT_DESTROY_CHECKPOINT\fP = 64, \fBSESSION_EVT_SAVE\fP = 128 }"
.br
.ti -1c
.RI "enum \fBomega_viewport_event_t\fP { \fBVIEWPORT_EVT_UNDEFINED\fP = 0, \fBVIEWPORT_EVT_CREATE\fP = 1, \fBVIEWPORT_EVT_EDIT\fP = 2, \fBVIEWPORT_EVT_UNDO\fP = 4, \fBVIEWPORT_EVT_CLEAR\fP = 8, \fBVIEWPORT_EVT_TRANSFORM\fP = 16, \fBVIEWPORT_EVT_UPDATED\fP = 32 }"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct omega_change_struct \fBomega_change_t\fP"

.SS "typedef struct omega_session_struct \fBomega_session_t\fP"

.SS "typedef struct omega_viewport_struct \fBomega_viewport_t\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBomega_session_event_t\fP"
Enumeration of session events 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISESSION_EVT_UNDEFINED \fP\fP
.TP
\fB\fISESSION_EVT_CREATE \fP\fP
.TP
\fB\fISESSION_EVT_EDIT \fP\fP
.TP
\fB\fISESSION_EVT_UNDO \fP\fP
.TP
\fB\fISESSION_EVT_CLEAR \fP\fP
.TP
\fB\fISESSION_EVT_TRANSFORM \fP\fP
.TP
\fB\fISESSION_EVT_CREATE_CHECKPOINT \fP\fP
.TP
\fB\fISESSION_EVT_DESTROY_CHECKPOINT \fP\fP
.TP
\fB\fISESSION_EVT_SAVE \fP\fP
.SS "enum \fBomega_viewport_event_t\fP"
Enumeration of viewport events 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIVIEWPORT_EVT_UNDEFINED \fP\fP
.TP
\fB\fIVIEWPORT_EVT_CREATE \fP\fP
.TP
\fB\fIVIEWPORT_EVT_EDIT \fP\fP
.TP
\fB\fIVIEWPORT_EVT_UNDO \fP\fP
.TP
\fB\fIVIEWPORT_EVT_CLEAR \fP\fP
.TP
\fB\fIVIEWPORT_EVT_TRANSFORM \fP\fP
.TP
\fB\fIVIEWPORT_EVT_UPDATED \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for omega_edit from the source code\&.
