.TH "src/include/omega_edit/license.h" 3 "Thu Mar 3 2022" "Version 0.8.1" "omega_edit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/omega_edit/license.h
.SH SYNOPSIS
.br
.PP
\fC#include 'export\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBOMEGA_EDIT_EXPORT\fP const char * \fBomega_license_get\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBOMEGA_EDIT_EXPORT\fP const char * omega_license_get ()"
Gets the license text 
.PP
\fBReturns\fP
.RS 4
null-terminated license text 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for omega_edit from the source code\&.
