.TH "src/include/omega_edit.h" 3 "Wed Mar 2 2022" "Version 0.8.1" "omega_edit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/omega_edit.h
.SH SYNOPSIS
.br
.PP
\fC#include 'omega_edit/change\&.h'\fP
.br
\fC#include 'omega_edit/edit\&.h'\fP
.br
\fC#include 'omega_edit/license\&.h'\fP
.br
\fC#include 'omega_edit/search\&.h'\fP
.br
\fC#include 'omega_edit/session\&.h'\fP
.br
\fC#include 'omega_edit/version\&.h'\fP
.br
\fC#include 'omega_edit/viewport\&.h'\fP
.br
\fC#include 'omega_edit/visit\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for omega_edit from the source code\&.
