.TH "src/include/omega_edit/stl_string_adaptor.hpp" 3 "Thu Mar 3 2022" "Version 0.8.1" "omega_edit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/omega_edit/stl_string_adaptor.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'export\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for omega_edit from the source code\&.
