.TH "src/include/omega_edit/version.h" 3 "Thu Mar 3 2022" "Version 0.8.1" "omega_edit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/omega_edit/version.h
.SH SYNOPSIS
.br
.PP
\fC#include 'export\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBOMEGA_EDIT_EXPORT\fP int \fBomega_version_major\fP ()"
.br
.ti -1c
.RI "\fBOMEGA_EDIT_EXPORT\fP int \fBomega_version_minor\fP ()"
.br
.ti -1c
.RI "\fBOMEGA_EDIT_EXPORT\fP int \fBomega_version_patch\fP ()"
.br
.ti -1c
.RI "\fBOMEGA_EDIT_EXPORT\fP int \fBomega_version\fP ()"
.br
.ti -1c
.RI "\fBOMEGA_EDIT_EXPORT\fP char const * \fBomega_libtype\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBOMEGA_EDIT_EXPORT\fP char const  * omega_libtype ()"
Returns 'shared' if the library has been built as a shared library, or 'static' if the library is built as a static library 
.PP
\fBReturns\fP
.RS 4
'shared' if the library has been built as a shared library, or 'static' if the library is built as a static library 
.RE
.PP

.SS "\fBOMEGA_EDIT_EXPORT\fP int omega_version ()"
Get the integer representation of the version of the library 
.PP
\fBReturns\fP
.RS 4
the integer representation of the version of the library 
.RE
.PP

.SS "\fBOMEGA_EDIT_EXPORT\fP int omega_version_major ()"
Get the major version of the library 
.PP
\fBReturns\fP
.RS 4
the major version of the library 
.RE
.PP

.SS "\fBOMEGA_EDIT_EXPORT\fP int omega_version_minor ()"
Get the minor version of the library 
.PP
\fBReturns\fP
.RS 4
the minor version of the library 
.RE
.PP

.SS "\fBOMEGA_EDIT_EXPORT\fP int omega_version_patch ()"
Get the patch-level of the library 
.PP
\fBReturns\fP
.RS 4
the patch-level of the library 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for omega_edit from the source code\&.
