---
name: License Header Check
on:
  push:
    branches:
      - '**'

jobs:
  headers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: C/C++ source and header check
        run: |
          ! grep -R -L --exclude-dir=vendor \
            --include='*.c' --include='*.cpp' --include='*.h' --include='*.hpp' \
            'Copyright (c) 2021 Concurrent Technologies Corporation' *
