# Copyright (c) 2021 Concurrent Technologies Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software is distributed under the License is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.  See the License for the specific language governing permissions and limitations under the License.

---
name: TypeScript Formatting

permissions: {}

on:
  pull_request:
    branches: ['**']

jobs:
  build:
    name: TypeScript code is properly formatted
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: 14

      - name: Yarn - Install
        run: yarn install
        shell: bash
        working-directory: src/rpc/client/ts
      
      - name: Yarn - Lint
        run: yarn lint
        shell: bash
        working-directory: src/rpc/client/ts
